"baseURL = "https://sysbl1nk.github.io/"
languageCode = "es"
title = "Pwnd blog"
theme = "hugo-simple"

[params]
  description = "Blog hecho con Org mode y Hugo"

  [params.author]
    name = "sysbl1nk"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
